# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
library(log4r)
library(jsonlite)

library(parsnip)
library(recipes)
library(stats)
library(workflows)

# get the model
board <- pins::board_local()
v <- board %>% vetiver_pin_read("flights_fit")



get_log_object <- function(log_type, sessionID){
  my_layout <- function(level, ...) {
    paste0(level, " [", format(Sys.time()), "] [", sessionID, "] "
           , ..., "\n", collapse = "")
  }

  log_obj <- create.logger(logfile = here::here('logs',
                                                        log_type,
                                                        paste0(Sys.Date(), ".log")),
                                   level = "DEBUG")

  log_obj <- logger(appenders = file_appender(file = here::here('logs',
                                                                        log_type,
                                                                        paste0(Sys.Date(), ".log")),
                                                      layout = my_layout))

  return(log_obj)
}



#* The predict endpoint
#* @get /ping
function(res, req){
  return()
}

#* The predict endpoint
#* @post /predict_flights
function(res, req){
  # for simplicity we leave all the code to reate logs here.
  # in a more robust set up, you might want to use a filter function to define
  # logs
  sessionID <- sample(seq(1, 1e6), 1)
  logger_requests <- get_log_object('requests', sessionID)
  logger_responses <- get_log_object('responses', sessionID)
  logger_performance <- get_log_object('performance', sessionID)


  info(logger_requests, jsonlite::toJSON(req$body))
  req$body$date <- lubridate::as_date(req$body$date)
  req$body$time_hour <- lubridate::as_date(req$body$time_hour)

  time_elapsed <- system.time({preds <- stats::predict(v, req$body)})
  time_elapsed <- jsonlite::toJSON(as.data.frame(t(data.matrix(time_elapsed))))

  info(logger_performance, time_elapsed)
  info(logger_responses, jsonlite::toJSON(preds))

  return(preds)
}
